### ISSUE TITLE
Проверки на проверки

### ISSUE THREAD

**Issue by png-tech** [MakarovEvgeny/validations#21]
Нужно ограничить лень аналитики следующими проверками. 

1. Нельзя создавать новую версию без поля комментарий.
2. Если есть предыдущая версия, то комментарий предыдущей версии должен отличаться. 
3. Для создания новой версии проверки должно измениться либо описание, либо тип, либо привязки проверки.

**Comment by MakarovEvgeny** [comment]
Я правильно понял, что комментарий должен быть указан для каждой версии (в том числе и при создании)?

**Comment by MakarovEvgeny** [comment]
Пункт 3 - не реализовано, слишком жесткие ограничения.
