### ISSUE TITLE
Логировать конфиденциальную информацию не надо

### ISSUE THREAD

**Issue by MakarovEvgeny** [MakarovEvgeny/validations#24]
В случае регистрации нового пользователя в табличку с логами попадает пароль в открытом виде

**Comment by png-tech** [comment]
Идея решения. 

Доработка решения с аспектом и логированием: 
1. Вытаскиваем из аспекта логику с  ObjectWriter. Флаг logResult удаляем из аннотации аспекта.
2. Делаем интерфейс JsonLogger{ String logResponse(Object); String logRequest(Object);}.
3. Делаем 3 реализации DefaultLogger, ExportExcelLogger, SecurityLogger.
4. под них делаем 3 бина в spring.
5. В аннотации прописываем доп. параметр класс logger-а со значением по умолчанию DefaultLogger.

Доработка security
1. Добавляем в users новое поле "Дата регистрации" not null
2. Пишем его в java  и отдаем в клиент на карточку.


PS: Названия классов и интерфейсов - примерные, чтобы понять суть, нужно проработать как лучше их назвать.

**Comment by MakarovEvgeny** [comment]
> Добавляем в users новое поле "Дата регистрации" not null
Заведена задача #25 

> Пишем его в java и отдаем в клиент на карточку.
На клиенте эта информация пока не нужна.
